using System;
using System.Collections.Generic;
using System.Text;

namespace NextGen.ControlMapping
{   public class RAItems
    {
        public string RAType { get; set; }
        public string PriorPolicyNumber { get; set; }
        public string LegalEntityType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BusinessName { get; set; }
        public string BusinessNameID { get; set; }
        public string FEIN { get; set; }
        public string FEINID { get; set; }
        public string BusinessClass { get; set; }
        public string BusinessClassSubClass { get; set; }
        public string AddressLineOne { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string BusinessLiabilityLimit { get; set; }
        public string MedicalExpensesLimit { get; set; }
        public string DamageToPremises { get; set; }
        public string AddTerrorismCoverage { get; set; }
        public string CauseOfLoss { get; set; }
        public string InflationGuard { get; set; }
        public string BlanketToolsAndEquipment { get; set; }
        public string EmployeeBenefitsNumOfEmployees { get; set; }
        public string DoesTheInsuredProvideAnyDeliveryServices { get; set; }
        public string DoesTheInsuredProvideAnyDeliveryServicesCoverageNumber { get; set; }
        public string EmployeeBenefitsRetroactiveDate { get; set; }
        public string EmployeeDishonesty { get; set; }
         public string EmployeeDishonestyLimitt { get; set; }
        public string EmployeeDishonestyNumOfEmployees { get; set; }
        public string EmployeeDishonestyNumOfLocations { get; set; }
        public string EmployeesTools { get; set; }
        public string EmployeesToolsLimitAmountID { get; set; }
        public string ForgeryAndAlteration { get; set; }
        public string AutoInsurer { get; set; }
        public string PolicyNumber { get; set; }
        public string ProductType { get; set; }
        public string EffectiveDate { get; set; }
        public string InstallationCoverage { get; set; }
        public string NonOwnedToolsAndEquipment { get; set; }
        public string NonOwnedToolsAndEquipmentCoverageID { get; set; }
        public string SalesAndDisposalLegalLiability { get; set; }
        public string CustomerGoodsLegalLiability { get; set; }
        public string AnnualRevenue { get; set; }
        public string Company { get; set; }
        public string County { get; set; }
        public string ProtectionClass { get; set; }
        public string CoastalDistance { get; set; }
        public string HiredAndNonOwnedAutoLiability { get; set; }
        public string HiredAndNonOwnedAutoLiabilityNo { get; set; }
        public string HiredAndNonOwnedAutoLiabilityCoverageNumber { get; set; }
        public string DoesTheInsuredProvideAnyshuttleServices { get; set; }
        public string DoesTheInsuredProvideAnyshuttleServicesCoverageNumber { get; set; }
        public string BusinessIncomeWithExtraExpenseMonthIndemnityCoverageNumber { get; set; }
        public string ExcludeWindHail { get; set; }
        public string DeductibleType { get; set; }
        public string AllOtherPerilsDeductible { get; set; }
        public string HurricaneDeductible { get; set; }
        public string WindHailDeductible { get; set; }        
        public string DoesTheApplicantProvideAGym { get; set; }
        public string totalResidentialUnits { get; set; }
        public string Type { get; set; }
        public string sitesAndRentalUnitsRentalUnits { get; set; }
        public string TotalNumberOfSwimmingPoolsSpas { get; set; }
        public string TotalNumberOfPonds { get; set; }
        public string DivingPlatform { get; set; }
        public string Slide { get; set; }
        public string yearParkEstablished { get; set; }
        public string perOfUnpavdCmmnSt { get; set; }
        public string allCommnStLighted { get; set; }
        public string NumberofCamperTentSites { get; set; }
        public string TotalParkingAreaowned { get; set; }
        public string AccountReceivable { get; set; }
        public string BusinessIncomeWithExtraExpense { get; set; }
        public string BusinessIncomeWithExtraExpenseCoverageNumber { get; set; }
        public string BusinessIncomeWithExtraExpenseType { get; set; }
        public string BusinessIncomeWithExtraExpenseLimitAmount { get; set; }
        public string BusinessIncomeWithExtraExpenseMonthIndemnity { get; set; }
        public string BusinessIncomeOrdinaryPayroll { get; set; }
        public string BusinessIncomeExtendedCoverage { get; set; }
        public string BusinessIncomeExtendedCoverageLimitAmount { get; set; }
        public string BusinessIncomeExtendedCoverageNumberOfDays { get; set; }
        public string BusinessIncomeExtendedCoverageNumberOfDaysCoverageNumber { get; set; }
        public string DebrisRemovalAddionalInsurance { get; set; }
        public string DebrisRemovalAddionalInsuranceCoverageNumber { get; set; }
        public string EquipmentBreakDown { get; set; }
        public string FineArtCoverage { get; set; }
        public string MoneyAndSecurities { get; set; }
        public string OutDoorSigns { get; set; }
        public string OutDoorSignsCoverageNumber { get; set; }
        public string PropertyDamageLegalLiability { get; set; }
        public string PropertyDamageLegalLiabilityCoverageNumber { get; set; }
        public string SinkholeLossCoverage { get; set; }
        public string SinkholeLossCoverageCoverageNumber { get; set; }
        public int SpecialClassPropertyCount { get; set; }
        public string SpecialClassProperty { get; set; }
        public List<string> SpecialClassPropertyType { get; set; }
        public List<string> SpecialClassPropertyLimit { get; set; }
        public string SpecialClassProperty2 { get; set; }
        public string SpecialClassPropertyType2 { get; set; }
        public string SpecialClassPropertyLimit2 { get; set; }
        public string SpecialClassProperty3 { get; set; }
        public string SpecialClassPropertyType3 { get; set; }
        public string SpecialClassPropertyLimit3 { get; set; }
        public string UtilityServicesDirectDamage { get; set; }
        public string UtilityServicesDirectDamageLimitAmount { get; set; }
        public string UtilityServicesDirectDamageLimitAmountCoverageNumber { get; set; }
        public string UtilityServicesDirectDamageOverheadPower { get; set; }
        public string UtilityServicesDirectDamageOverheadPowerCoverageNumber { get; set; }
        public string UtilityServicesTimeElement { get; set; }
        public string UtilityServicesTimeElementLimitAmount { get; set; }
        public string UtilityServicesTimeElementLimitAmountCoverageNumber { get; set; }
        public string UtilityServicesTimeElementOverheadPower { get; set; }
        public string UtilityServicesTimeElementOverheadPowerCoverageNumber { get; set; }
        public string WaterBackupAndSumpOverflowCoverage { get; set; }
        public string WaterBackupAndSumpOverflowCoverageCoverageNumber { get; set; }
        public string PollutantRemovalCleanUpCoverage { get; set; }
        public string ExposuresList { get; set; }
        public string ExposureType { get; set; }
        public string OfficeCoverageType { get; set; }
        public string SalesTotal { get; set; }
        public string VacantLand { get; set; }
        public string ParkAndPLaygroundDescription { get; set; }
        public string RacquetBallArea { get; set; }
        public string NumberOfStories { get; set; }
        public string YearBuilt { get; set; }
        public string SquareFeet { get; set; }
        public string ContructionType { get; set; }
        public string RoofType { get; set; }
        public string RoofingMaterial { get; set; }
        public string OpeningProtectionType { get; set; }
        public string ProtectiveSafeGuard { get; set; }
        public string ProtectiveSafeGuardYesNo { get; set; }
        public string PercentUsedforResidential { get; set; }
        public string BuildingCodeGrade { get; set; }
        public string IsThisBuildingLessThan30PercentOccupied { get; set; }
        public string HotelMotelType { get; set; }
        public string ReinforcedConcreteRoof { get; set; }
        public string ReinforcedConcreteWall { get; set; }
        public string BuildingLimit { get; set; }
        public string BussinessPersonalPropertyLimit { get; set; }
        public string BuildingImprovements { get; set; }
        public string WiringYear { get; set; }
        public string PlumbingYear { get; set; }
        public string RoofingYear { get; set; }
        public string HeatingYear { get; set; }
        public string AirConditioningYear { get; set; }
        public string WindMitigationVerificationFormCompleted { get; set; }
        public string OrdinanceLawCoverage1 { get; set; }
        public string OrdinanceLawCoverage1_2_3Combined { get; set; }
        public string OrdinanceLawCoverage3ForIncresedCostofConstruction { get; set; }
        public string OrdinanceLawCoverage2_3CombinedforDemolition { get; set; }
        public string OrdinanceLawCoverage2_3CombinedforDemolitionSelectLimit { get; set; }
        public string OrdinanceLawCoverage2_3CombinedforDemolitionCoverageNumber { get; set; }
        public string OrdinanceLawCoverage2_3CombinedforDemolitionLimitAmount { get; set; }
        public string OrdinanceLawCoverage2_3CombinedforDemolitionLimitAmountCovergaeNumber { get; set; }
        public string SpoilageLimit { get; set; }
        public string SpoilageDeductible { get; set; }
        public string Description { get; set; }
        public string ValuablePapers { get; set; }
        public string ValuablePapersLimitAmount { get; set; }
        public string intType { get; set; }
        public string cancelNotice { get; set; }
        public string InterestType { get; set; }
        public string CancellationNoticeIsToAppear { get; set; }
        public string LoanNumber { get; set; }
        public string Forms { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string TownCity { get; set; }
        public string State { get; set; }
        public string QIState { get; set; }

        public string ZipCode { get; set; }

    }
}
